### ISSUE TITLE
Folder location needs changing 2020 macos

### ISSUE THREAD

**Issue by cjrobbertse** [galCohen88/pycharm-jenkinsfile#2]

**Comment by EdwinaZhao** [comment]
I can't find the folder path in the MBP.

**Comment by galCohen88** [comment]
@EdwinaZhao I'm using MBP, have you tried looking for `PyCharm` folder prefix under `~/Library/Preferences/`?

**Comment by galCohen88** [comment]
@EdwinaZhao following https://www.jetbrains.com/help/idea/tuning-the-ide.html#config-directory the directory have been changed, I will create a PR for your review

**Comment by galCohen88** [comment]
@EdwinaZhao Can you please review https://github.com/galCohen88/pycharm-jenkinsfile/pull/3

**Comment by galCohen88** [comment]
CC @cjrobbertse

**Comment by cjrobbertse** [comment]
@galCohen88 I have now found `~/Library/Preferences/PyCharm2019.2/`, but there is no `filetypes` folder inside

**Comment by galCohen88** [comment]
@cjrobbertse did you see the new changes for README.md file?

**Comment by cjrobbertse** [comment]
Ahh yes, I see. Thanks a lot @galCohen88 👍
