### ISSUE TITLE
can't find filetype on new path in Pycharm 2020.3

### ISSUE THREAD

**Issue by michaelpecan** [galCohen88/pycharm-jenkinsfile#4]
macos catalina

**Comment by EdwinaZhao** [comment]
If you can't find the `filetype`, you may need to create a new folder named `filetype`.
Here is my path:  `~/Library/Application Support/JetBrains/PyCharm2020.2/filetypes`

**Comment by michaelpecan** [comment]
added the folder fixed it, thanks
